---
- hosts: all
  gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_user: alethea
    ansible_become: True
    ansible_password: alethea123
    ansible_become_method: enable
    ansible_become_pass: alethea123
    ansible_command_timeout: 80

  tasks:
  # - name: set the motd on remote devices
  #   icx_banner:
  #     banner: motd
  #     text: |
  #       welcome motd
  #       multiline
  #       string
  #     # check_running_config : True 
  #   register: output
   
  # - name: show command
  #   debug:
  #    msg: '{{ output }}'

  - name: set the incoming on remote devices
    icx_banner:
      banner: motd
      text: |
        welcome motd
        multiline
        string kjhjkh
    register: output
   
  - name: show command
    debug:
     msg: '{{ output }}'    

  # - name: set the exec on remote devices
  #   icx_banner:
  #     banner: exec
  #     text: |
  #       welcome
  #       multiline
  #       string
  #   register: output
   
  # - name: show command
  #   debug:
  #    msg: '{{ output }}'

  # - name: set the motd on remote devices
  #   icx_banner:
  #     banner: motd
  #     text: welcome motd
  #   check_mode: yes
  #   register: output
   
  # - name: show command
  #   debug:
  #    msg: '{{ output }}'

  # - name: set the incoming on remote devices
  #   icx_banner:
  #     banner: incoming
  #     text: welcome incoming
  #   register: output
   
  # - name: show command
  #   debug:
  #    msg: '{{ output }}'    

  # - name: set the exec on remote devices
  #   icx_banner:
  #     banner: exec
  #     text: welcome
  #   register: output
   
  # - name: show command
  #   debug:
  #    msg: '{{ output }}'
  
  # - name: remove motd on remote devices
  #   icx_banner:
  #     banner: motd
  #     state: absent
  #   register: output
   
  # - name: show command
  #   debug:
  #    msg: '{{ output }}'

  # - name: remove incoming on remote devices
  #   icx_banner:
  #     banner: incoming
  #     state: absent
  #   register: output
   
  # - name: show command
  #   debug:
  #    msg: '{{ output }}'    

  # - name: remove exec on remote devices
  #   icx_banner:
  #     banner: exec
  #     state: absent
  #   register: output
   
  # - name: show command
  #   debug:
  #    msg: '{{ output }}'
  

  # - name: set the enterkey motd on remote devices
  #   icx_banner:
  #     banner: motd
  #     text: welcome motd with enterkey
  #     enterkey: False
  #   register: output
   
  # - name: show command
  #   debug:
  #    msg: '{{ output }}'
