---
- hosts: icx
  #gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_user: alethea
    ansible_become: True
    ansible_password: alethea123
    ansible_become_method: enable
    ansible_become_pass: alethea123
    ansible_command_timeout: 60

  tasks:
    # - name: Collect the default facts
    #   icx_facts:
    #     gather_subset:
    #       - default
    #   register: result

    # - name: Collect the hardware facts
    #   icx_facts:
    #     gather_subset:
    #       - hardware
    #   register: result

    # - name: Collect the config facts
    #   icx_facts:
    #     gather_subset:
    #       - config
    #   register: result

    - name: Collect the interfaces facts
      icx_facts:
        gather_subset:
          - interfaces
      register: result

    # - name: Collect all the facts
    #   icx_facts:
    #     gather_subset:
    #       - all
    #   register: result

    - name: debug
      debug:
        var: result