---
- hosts: 10.10.10.182
  gather_facts: yes
  vars:
    ansible_network_os: icx
    ansible_become: True
    ansible_user: alethea
    ansible_password: alethea123
    ansible_become_method: enable
    ansible_become_pass: alethea123
    
        
  tasks:
  - name: configure static route
    icx_static_route:
      prefix: 192.128.2.0/24
      next_hop: 10.10.14.3
      state: absent
      compare: false
      
  # - name: configure 32 length static route
  #   icx_static_route:
  #     prefix: 192.128.2.1
  #     mask: 255.255.255.0
  #     next_hop: 10.10.14.3
  #     state: present
      
  # - name: configure static route with distance
  #   icx_static_route:
  #     prefix: 192.128.21.0
  #     mask: 255.255.255.0
  #     next_hop: 10.10.14.1
  #     admin_distance: 30
  #     state: absent     

  
  # - name: aggregate config
  #   icx_static_route:
  #    aggregate:
  #     - {prefix: 192.128.0.0}
  #     - {prefix: 192.126.23.0}
  #    next_hop: 10.10.15.31
  #    mask: 255.255.255.0
     
    #  purge: true
    
    
    register: output
      
  - debug:
      msg: '{{ output }}'
      
      