---
- hosts: 10.10.10.182
  gather_facts: yes
  vars:
    ansible_network_os: icx
    ansible_become: True
    ansible_user: alethea
    ansible_password: alethea123
    ansible_become_method: enable
    ansible_become_pass: alethea123
    
        
  tasks:
  - name: disable lldp service
    icx_lldp:
      interfaces:
        - name: ethernet 1/1/1 to 1/1/6
          state: present
  # - name: enable lldp on ports(fail)
  #   icx_lldp:
  #     interfaces:
  #       - name: ethernet 1/1/1 to 1/1/6
  #         state: present
    
  # - name: enable lldp on ports when state = present
  #   icx_lldp:
  #     interfaces:
  #      - name: 
  #         - ethernet 1/1/1 to 1/1/48 ethernet 1/1/49
  #        state: absent
  #     state: present

  # - name: disable lldp on ports when state = None and lldp service is enabled
  #   icx_lldp:
  #     interfaces:
  #       - name: ethernet 1/1/1 to 1/1/48 ethernet 1/1/49
  #         state: absent

  #   register: output
  # - name: show command
  #   debug:
  #     msg: '{{ output }}'
