---
- hosts: 10.10.10.182
  # gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_user: alethea
    ansible_become: True
    ansible_password: alethea123
    ansible_become_method: enable
    ansible_become_pass: alethea123
    ansible_command_timeout: 60

  tasks:
    - name: set ipv4 address
      icx_l3_interface:
        name: ethernet 1/1/1
        ipv4: 192.168.4.2/24
        # replace: yes
        # mode: dynamic
        # secondary: yes
        # state: absent
        compare: true
      register: result

    - debug:
        var: result

    # - name: set ipv6 address
    #   icx_l3_interface:
    #     name: ethernet 1/1/1
    #     ipv6: "2001:db8:85a3:1:1:1:1:1/64"
    #   register: result

    # - debug:
    #     var: result

    # - name: remove ipv6 address
    #   icx_l3_interface:
    #     name: ethernet 1/1/1
    #     ipv6: "2001:db8:85a3:1:1:1:1:1/64"
    #     state: "absent"
    #   register: result

    # - debug:
    #     var: result

    # - name: set ipv6, ipv4 and using aggregate
    #   icx_l3_interface:
    #     aggregate:
    #       - {name: "ethernet 1/1/1", ipv6: "2001:db8:85a5:1:1:1:1:2/64"}
    #       - {name: "ethernet 1/1/1", ipv6: "2001:db8:85a6:1:1:1:1:3/64"}
    #       - {name: "ethernet 1/1/1", ipv6: "2001:db8:85a6:1:1:1:1:5/64"}
    #       - {name: "ve 1", ipv6: "2001:db8:85a4:1:1:1:1:2/64", ipv4: "192.168.101.1/24"}
    #     # state: absent
    #   register: result

    - debug:
        var: result
